FROM node:24-alpine3.21

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the remaining application files to the working directory
COPY . .

# Build the application
RUN npm run build

# Expose port 5002 for the application
EXPOSE 5002

# Start the application
CMD [ "npm", "run", "dev" ]
